version: "3"
services:
  nats:
    image: nats-streaming
    restart: always
    ports:
      - 4222
    command: "--dir /data"
    volumes:
      - ./nats-store:/data
  etcd:
    image: quay.io/coreos/etcd
    restart: always
    entrypoint: etcd
    command: >
      --data-dir=/data --name etcd1
      --advertise-client-urls http://etcd:2379
      --listen-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-cluster-token etcd-cluster-token
      --initial-cluster "etcd1=http://etcd:2380"
      --initial-advertise-peer-urls "http://etcd:2380"
      --initial-cluster-state new
    volumes:
      - ./etcd-data:/data
    ports:
      - 2379:2379
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_PASSWORD=123456
  go2o:
    image: docker-base.56x.net:5020/go2o
    depends_on:
      - "postgres"
      - "nats"
      - "etcd"
    restart: always
    ports:
      - "1427:1427"
      - "1428:1428"
    volumes:
      - ./go2o:/data
    environment:
      GO2O_NATS_ADDR: nats:4222
      GO2O_ETCD_ADDR: etcd:2379